apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elastic-enterprisesearch-keys
  labels: {{ include "enterprisesearch.labels" . | nindent 4 }}
spec:
  storageClassName: elastic-enterprisesearch-keys
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi